---
name: Module-Build-Functions
version: 0.001_010
author:
  - 'Curtis Jewell <csjewell@cpan.org>'
abstract: Module::Install style syntax for Module::Build
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Capture::Tiny: 0.06
  Module::Build: 0.31
  Test::Compile: 0
  Test::More: 0
requires:
  File::Slurp: 0
  Module::Build: 0.07
  perl: 5.00503
configure_requires:
  Module::Build: 0.31
provides:
  Module::Build::Functions:
    file: lib/Module/Build/Functions.pm
    version: 0.001_010
generated_by: Module::Build version 0.3303
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
